name: node-cert-exporter
base: core22
adopt-info: node-cert-exporter
summary: Node Cert Exporter
description: |
  Node Cert Exporter (node-cert-exporter) is an exporter that exposes
  certificate expiration information for use by the Prometheus monitoring
  system.
grade: stable
confinement: strict

apps:
  node-cert-exporter:
    daemon: simple
    restart-condition: on-abnormal
    command: "bin/node-cert-exporter.wrapper"
    plugs:
      - etc-ovn
      - etc-neutron
      - network-bind

parts:
  node-cert-exporter:
    plugin: go
    source: https://github.com/amimof/node-cert-exporter.git
    source-tag: v1.1.4
    source-type: git
    build-snaps:
      - go
    override-pull: |
      craftctl default
      TAG=$(git describe --tags --abbrev=10)
      craftctl set version="${TAG#v}"
  scripts:
    plugin: dump
    source: scripts
    organize:
      node-cert-exporter.wrapper: "bin/node-cert-exporter.wrapper"

plugs:
  etc-ovn:
    interface: system-files
    read:
    - /etc/ovn
  etc-neutron:
    interface: system-files
    read:
    - /etc/neutron
